// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

export const SEARCH_TOKEN_TO_ID: Map<string, string[]> = new Map<string, string[]>([
    ["Ids", "Id"],
    ["Ips", "Ip"],
    ["Hostnames", "Hostname"],
    ["EndpointIpAddresses", ["Endpoints", "IpAddress"]],
    ["Ports", ["Endpoints", "Port"]],
    ["Protocols", ["Endpoints", "Protocol"]],
    ["WebUrlPaths", ["Endpoints", "WebUrlPath"]],
    ["DefaultDnsNames", "DefaultDnsName"],
    ["Versions", "Version"],
    ["SessionManagerAgentVersions", "SessionManagerAgentVersion"],
    ["Availabilities", "Availability"],
    ["UnavailabilityReasons", "UnavailabilityReason"],
    ["ConsoleSessionCounts", "ConsoleSessionCount"],
    ["VirtualSessionCounts", "VirtualSessionCount"],
    ["OsFamilies", "Host.Os.Family"],
    ["OsNames", "Host.Os.Name"],
    ["OsVersions", "Host.Os.Version"],
    ["OsKernelVersions", "Host.Os.KernelVersion"],
    ["OsBuildNumbers", "Host.Os.BuildNumber"],
    ["MemoryTotalBytes", "Host.Memory.TotalBytes"],
    ["MemoryUsedBytes", "Host.Memory.UsedBytes"],
    ["SwapTotalBytes", "Host.Swap.TotalBytes"],
    ["SwapUsedBytes", "Host.Swap.UsedBytes"],
    ["AwsRegions", "Host.Aws.Region"],
    ["AwsEc2InstanceTypes", "Host.Aws.EC2InstanceType"],
    ["AwsEc2InstanceIds", "Host.Aws.EC2InstanceId"],
    ["AwsEc2ImageIds", "Host.Aws.EC2ImageId"],
    ["CpuVendors", "Host.CpuInfo.Vendor"],
    ["CpuModelNames", "Host.CpuInfo.ModelName"],
    ["CpuArchitectures", "Host.CpuInfo.Architecture"],
    ["NumberOfCpus", "Host.CpuInfo.NumberOfCpus"],
    ["PhysicalCorePerCpus", "Host.CpuInfo.PhysicalCoresPerCpu"],
    ["CpuLoadOneMinuteAverages", "Host.CpuLoadAverage.OneMinute"],
    ["CpuLoadFiveMinuteAverages", "Host.CpuLoadAverage.FiveMinutes"],
    ["CpuLoadFifteenMinuteAverages", "Host.CpuLoadAverage.FifteenMinutes"],
    ["GpuVendors", ["Host.Gpus", "Vendor"]],
    ["GpuModelName", ["Host.Gpus", "ModelName"]],
    ["LoggedInUsers", ["Host.LoggedInUsers", "Username"]],
    ["Tags", "Tags"],
])

export const TOKEN_NAMES_MAP: Record<string, string> = {
    "Ids": "Server Id",
    "Ips": "IP",
    "Hostnames": "Hostname",
    "EndpointIpAddresses": "Endpoint IP address",
    "Ports": "Port",
    "Protocols": "Protocol",
    "WebUrlPaths": "Web URL path",
    "DefaultDnsNames": "Default DNS name",
    "Versions": "Amazon DCV server version",
    "SessionManagerAgentVersion": "Session Manager agent version",
    "Availabilities": "Availability",
    "UnavailabilityReasons": "Unavailability reason",
    "ConsoleSessionCounts": "Console session count",
    "VirtualSessionCounts": "Virtual session count",
    "OsFamilies": "OS family",
    "OsNames": "OS name",
    "OsVersions": "OS version",
    "OsKernelVersions": "OS kernel version",
    "OsBuildNumbers": "OS build number",
    "MemoryTotalBytes": "Memory total bytes",
    "MemoryUsedBytes": "Memory used bytes",
    "SwapTotalBytes": "Swap total bytes",
    "SwapUsedBytes": "Swap used bytes",
    "AwsRegions": "AWS region",
    "AwsEc2InstanceTypes": "AWS EC2 instance type",
    "AwsEc2InstanceIds": "AWS EC2 instance Id",
    "AwsEc2ImageIds": "AWS EC2 image Id",
    "CpuVendors": "CPU vendor",
    "CpuModelNames": "CPU model name",
    "CpuArchitectures": "CPU architecture",
    "NumberOfCpus": "Number of CPUs",
    "PhysicalCorePerCpus": "Physical core per CPU",
    "CpuLoadOneMinuteAverages": "CPU load one minute average",
    "CpuLoadFiveMinuteAverages": "CPU load five minute average",
    "CpuLoadFifteenMinuteAverages": "CPU load fifteen minute average",
    "GpuVendors": "GPU vendor",
    "GpuModelName": "GPU model name",
    "LoggedInUsers": "Logged in users",
    "Tags": "Tags"
}

export const TOKEN_NAME_GROUP_MAP: Record<string, string> = {
    "Ids": "Server Id values",
    "Ips": "IP values",
    "Hostnames": "Hostname values",
    "EndpointIpAddresses": "Endpoint IP address values",
    "Ports": "Port values",
    "Protocols": "Protocol values",
    "WebUrlPaths": "Web URL path values",
    "DefaultDnsNames": "Default DNS name values",
    "Versions": "Amazon DCV server version values",
    "SessionManagerAgentVersion": "Session Manager agent version values",
    "Availabilities": "Availability values",
    "UnavailabilityReasons": "Unavailability reason values",
    "ConsoleSessionCounts": "Console session count values",
    "VirtualSessionCounts": "Virtual session count values",
    "OsFamilies": "OS family values",
    "OsNames": "OS name values",
    "OsVersions": "OS version values",
    "OsKernelVersions": "OS kernel version values",
    "OsBuildNumbers": "OS build number values",
    "MemoryTotalBytes": "Memory total bytes values",
    "MemoryUsedBytes": "Memory used bytes values",
    "SwapTotalBytes": "Swap total bytes values",
    "SwapUsedBytes": "Swap used bytes values",
    "AwsRegions": "AWS region values",
    "AwsEc2InstanceTypes": "AWS EC2 instance type values",
    "AwsEc2InstanceIds": "AWS EC2 instance Id values",
    "AwsEc2ImageIds": "AWS EC2 image Id values",
    "CpuVendors": "CPU vendor values",
    "CpuModelNames": "CPU model name values",
    "CpuArchitectures": "CPU architecture values",
    "NumberOfCpus": "Number of CPUs values",
    "PhysicalCorePerCpus": "Physical core per CPU values",
    "CpuLoadOneMinuteAverages": "CPU load one minute average values",
    "CpuLoadFiveMinuteAverages": "CPU load five minute average values",
    "CpuLoadFifteenMinuteAverages": "CPU load fifteen minute average values",
    "GpuVendors": "GPU vendor values",
    "GpuModelName": "GPU model name values",
    "LoggedInUsers": "Logged in users values",
    "Tags": "Tags values"
}

export const FILTER_SERVER_CONSTANTS = {
    filteringPlaceholder: "Search hosts"
}
