export const SERVERS_TABLE_CONSTANTS = {
    LOADING_TEXT: "Loading hosts",
    EMPTY_TEXT: "No hosts",
    HEADER_TEXT: "Hosts",
    HEADER_DESCRIPTION: "All of your hosts with Amazon DCV servers are listed here.",
    BUTTON_TEXT: "View details",

    INFO_LINK: "https://docs.aws.amazon.com/dcv/latest/access-console/sessions.html",
    INFO_LABEL: "info",


    ID: "Id",
    IP_ID: "Ip",
    HOSTNAME_ID: "Hostname",
    DEFAULT_DNS_NAME_ID: "DefaultDnsName",
    ENDPOINTS_ID: "Endpoints",
    VERSION_ID: "Version",
    SESSION_MANAGER_AGENT_VERSION_ID: "SessionManagerAgentVersion",
    AVAILABILITY_ID: "Availability",
    UNAVAILABILITY_REASON_ID: "UnavailabilityReason",
    CONSOLE_SESSION_COUNT_ID: "ConsoleSessionCount",
    VIRTUAL_SESSION_COUNT_ID: "VirtualSessionCount",
    HOST_ID: "Host",
    TAGS_ID: "Tags",
    IPADDRESS_ID: "IpAddress",
    PORT_ID: "Port",
    WEB_URL_PATH_ID: "WebUrlPath",
    PROTOCOL_ID: "Protocol",
    OS_ID: "Os",
    MEMORY_ID: "Memory",
    SWAP_ID: "Swap",
    AWS_INSTANCE_TYPE_ID: "AwsInstanceType",
    CPU_INFO_ID: "CpuInfo",
    CPU_LOAD_AVERAGE_ID: "CpuLoadAverage",
    GPUS_ID: "Gpus",
    LOGGED_IN_USERS_ID: "LoggedInUsers",
    MEMORY_TOTAL_BYTES_ID: "MemoryTotalBytes",
    SWAP_TOTAL_BYTES_ID: "SwapTotalBytes",
    ID_HEADER: "Id",
    IP_HEADER: "Ip",
    HOSTNAME_HEADER: "Hostname",
    DEFAULT_DNS_NAME_HEADER: "Default DNS Name",
    ENDPOINTS_HEADER: "Endpoints",
    VERSION_HEADER: "Version",
    SESSION_MANAGER_AGENT_VERSION_HEADER: "Session Manager Agent Version",
    AVAILABILITY_HEADER: "Availability",
    UNAVAILABILITY_REASON_HEADER: "Unavailability Reason",
    CONSOLE_SESSION_COUNT_HEADER: "Console Session Count",
    VIRTUAL_SESSION_COUNT_HEADER: "Virtual Session Count",
    HOST_HEADER: "Host",
    TAGS_HEADER: "Tags",
    IPADDRESS_HEADER: "IpAddress",
    PORT_HEADER: "Port",
    WEB_URL_PATH_HEADER: "Web URL Path",
    PROTOCOL_HEADER: "Protocol",
    OS_HEADER: "Operating System",
    MEMORY_HEADER: "Memory",
    SWAP_HEADER: "Swap",
    AWS_INSTANCE_TYPE_HEADER: "Instance Type",
    CPU_HEADER: "CPU",
    CPU_INFO_HEADER: "CPU Info",
    CPU_LOAD_AVERAGE_HEADER: "CPU Load Average",
    GPUS_HEADER: "GPUs",
    LOGGED_IN_USERS_HEADER: "Logged in users",

    ENDPOINT_IP_ADDRESS_HEADER: "IpAddress",
    ENDPOINT_PORT_HEADER: "Port",
    ENDPOINT_PROTOCOL_HEADER: "Protocol",
    ENDPOINT_WEB_URL_PATH_HEADER: "Web URL Path",

    OS_FAMILY: "Family",
    OS_NAME: "Name",
    OS_VERSION: "Version",
    OS_KERNEL_VERSION: "Kernel",
    OS_BUILD_NUMBER: "Build number",

    MEMORY_TOTAL_BYTES: "Total bytes",
    MEMORY_USED_BYTES: "Used bytes",

    SWAP_TOTAL_BYTES: "Total bytes",
    SWAP_USED_BYTES: "Used bytes",

    AWS_HEADER: "AWS",
    AWS_REGION: "Region",
    AWS_EC2_INSTANCE_TYPE: "EC2 Instance Type",
    AWS_EC2_INSTANCE_ID: "EC2 Instance ID",
    AWS_EC2_IMAGE_ID: "EC2 Image ID",

    CPU_VENDOR: "Vendor",
    CPU_MODEL_NAME: "Model",
    CPU_ARCHITECTURE: "Architecture",
    CPU_NUMBER_OF_CPUS: "Number of vCPUs",
    CPU_PHYSICAL_CORE_PER_CPU: "Number of physical cores per CPU",

    CPU_LOAD_AVERAGE_ONE_MINUTE: "One Minute Average",
    CPU_LOAD_AVERAGE_FIVE_MINUTE: "Five Minute Average",
    CPU_LOAD_AVERAGE_FIFTEEN_MINUTE: "Fifteen Minute Average",

    GPU_VENDOR: "Vendor",
    GPU_MODEL_NAME: "Model",

    LOGGED_IN_USERS_USERNAME: "Username",
    UNKNOWN: "UNKNOWN"

}
