export const SESSION_TEMPLATES_CREATE_CONSTANTS = {
    CONFIGURE_DETAILS: "Configure template parameters",
    CONFIGURE_DESCRIPTION: "You create a session template by specifying the parameters here.",
    CONFIGURE_HEADER: "Template parameters",
    TEMPLATE_NAME: "Template name",
    NAME_DESCRIPTION: "This name will be shown to users.",
    NAME_PLACEHOLDER: "Template name",
    TEMPLATE_DESCRIPTION: "Template description",
    DESCRIPTION_DESCRIPTION: "Use this description to communicate the intended use for the template.",
    DESCRIPTION_PLACEHOLDER: "Describe the intended use of template.",
    OS: "Operating system",
    OS_DESCRIPTION: "Select the operating system of the host.",
    OS_VERSION: "Operating system version",
    OS_VERSION_DESCRIPTION: "Select the version for the host operating system.",
    OS_VERSION_PLACEHOLDER: "Select operating system version(s)",
    OS_VERSION_EMPTY_TEXT: "No operating system version found",
    OS_VERSION_LOADING_TEXT: "Loading operating system versions",
    OS_VERSION_CONTINUE_TEXT: "Start typing to search for an operating system version",
    TYPE: "Session type",
    TYPE_DESCRIPTION: "Select whether the session will be a console or a virtual session.",
    CONSOLE_DESCRIPTION: "One session on a Amazon DCV server at a time.",
    VIRTUAL_DESCRIPTION: "Multiple virtual sessions on a single Amazon DCV server.",
    OPENGL: "OpenGL",
    OPENGL_DESCRIPTION: "Enable to configure virtual sessions to use the hardware-based OpenGL.",
    INSTANCE: "EC2 Instance",
    INSTANCE_DESCRIPTION: "If you are running on EC2 instances, the following options are available.",
    INSTANCE_ID: "Instance ID",
    INSTANCE_ID_DESCRIPTION: "Select EC2 instance ID.",
    INSTANCE_ID_PLACEHOLDER: "Select instance ID(s)",
    INSTANCE_ID_EMPTY_TEXT: "No instance ID found",
    INSTANCE_ID_LOADING_TEXT: "Loading instance IDs",
    INSTANCE_ID_CONTINUE_TEXT: "Start typing to search for an instance ID",
    INSTANCE_ID_FILTERING_PROPERTY: "AwsEc2InstanceIds",
    INSTANCE_TYPE: "Instance type",
    INSTANCE_TYPE_DESCRIPTION: "Select the EC2 instance type and size.",
    INSTANCE_TYPE_PLACEHOLDER: "Select instance type(s)",
    INSTANCE_TYPE_EMPTY_TEXT: "No instance type found",
    INSTANCE_TYPE_LOADING_TEXT: "Loading instance types",
    INSTANCE_TYPE_CONTINUE_TEXT: "Start typing to search for an instance type",
    INSTANCE_TYPE_FILTERING_PROPERTY: "AwsEc2InstanceTypes",
    INSTANCE_REGION: "Instance region",
    INSTANCE_REGION_DESCRIPTION: "Select the EC2 instance region.",
    INSTANCE_REGION_PLACEHOLDER: "Select instance region(s)",
    INSTANCE_REGION_EMPTY_TEXT: "No instance region found",
    INSTANCE_REGION_LOADING_TEXT: "Loading instance regions",
    INSTANCE_REGION_CONTINUE_TEXT: "Start typing to search for an instance region",
    INSTANCE_REGION_FILTERING_PROPERTY: "AwsRegions",
    HOST: "Host",
    HOST_DESCRIPTION: "Parameters for the underlying host where Amazon DCV servers are installed.",
    HOST_NUM_OF_CPUS: "Number of vCPUs",
    HOST_NUM_OF_CPUS_DESCRIPTION: "Select the number of vCPUs for the host.",
    HOST_NUM_OF_CPUS_PLACEHOLDER: "Select the number of vCPUs",
    HOST_NUM_OF_CPUS_EMPTY_TEXT: "No number of vCPUs found",
    HOST_NUM_OF_CPUS_LOADING_TEXT: "Loading number of vCPUs",
    HOST_NUM_OF_CPUS_CONTINUE_TEXT: "Start typing to search for the number of vCPUs",
    HOST_NUM_OF_CPUS_FILTERING_PROPERTY: "NumberOfCpus",
    HOST_MEMORY: "Total memory",
    HOST_MEMORY_DESCRIPTION: "Select the total memory for the host.",
    HOST_MEMORY_PLACEHOLDER: "Select total memory",
    HOST_MEMORY_EMPTY_TEXT: "No total memory found",
    HOST_MEMORY_LOADING_TEXT: "Loading total memory",
    HOST_MEMORY_CONTINUE_TEXT: "Start typing to search for the total memory",
    HOST_MEMORY_FILTERING_PROPERTY: "MemoryTotalBytes",
    REQUIREMENTS: "Additional requirements",
    REQUIREMENTS_DESCRIPTION: "Additional requirements that the Amazon DCV server must satisfy. Parameters that you specified in the above form will pre-populate here. If you wish to edit these parameters, you must do so from the form itself. You can add additional requirements or logic here, including server tags and/or server properties.",
    REQUIREMENTS_INFO: "https://docs.aws.amazon.com/dcv/latest/access-console/session-templates.html#session-template-details",
    REQUIREMENTS_PLACEHOLDER: "tag:color = 'pink' and (server:Host.Os.Family = 'windows' or tag:color := 'red')\nserver:Host.Aws.Ec2InstanceType := 't2' and server:Host.CpuInfo.NumberOfCpus >= 2\"",
    AUTORUN: "Autorun",
    AUTORUN_FILE: "Autorun file path",
    AUTORUN_FILE_DESCRIPTION: "The file path to a custom scripts folder on the host. This is used to initialize Session Manager sessions when they are created.",
    AUTORUN_FILE_PLACEHOLDER: "/var/lib/dcv-session-manager-agent/init",
    AUTORUN_ARGUMENTS: "Autorun arguments",
    AUTORUN_ARGUMENTS_DESCRIPTION: "Command-line arguments that are passed to the autorun file when it is executed inside the session. Arguments are passed in the order they appear in the given array.",
    AUTORUN_ARGUMENTS_INFO: "",
    AUTORUN_ARGUMENTS_PLACEHOLDER: "Autorun arguments",
    ADDITIONAL_CONFIGURATIONS: "Advanced configurations",
    MAX_CONCURRENT_CLIENTS: "Max concurrent clients",
    MAX_CONCURRENT_CLIENTS_DESCRIPTION: "The maximum number of clients allowed to connect to a session at a given time. Set to “0” for no maximum.",
    INIT_FILE: "Init file path",
    INIT_FILE_DESCRIPTION: "Specifies the path to a folder on the host server used to store custom scripts allowed to initialize Session manager Sessions when they are created. Note: for Linux",
    INIT_FILE_PLACEHOLDER: "/var/lib/dcv-session-manager-agent/init",
    STORAGE_ROOT: "Storage root",
    STORAGE_ROOT_DESCRIPTION: "The file path to a folder for session storage.",
    STORAGE_ROOT_PLACEHOLDER: "%home%/storage/",

    SAVE: "Save",
    ASSIGN_USERS: "Assign users and groups",
    ASSIGN_USERS_ERROR: "Unable to assign users and groups: Error while obtaining session template information",
    DUPLICATE: "Duplicate",
    DUPLICATE_ERROR: "Unable to duplicate session template: Error while obtaining session template information",
    EDIT: "Edit",
    EDIT_ERROR: "Unable to edit session template: Error while obtaining session template information",
    EDIT_ALERT: "Editing an existing template could affect users already assigned to it. Any changes you make will not affect the sessions already created. However, it will affect users the next time they create a session using the modified template.",
    DELETE: "Delete",
    ASSIGN_USERS_DESCRIPTION: "You can assign users and groups to this template, so they may use it to create sessions.",
    REVIEW_AND_CREATE: "Review and create",
    REVIEW_AND_UPDATE: "Review and update",
    USERS: "Users",
    GROUPS: "Groups",
    USERS_OR_GROUPS: "Users and groups",
    USER: "User",
    GROUP: "Group",
    USERS_PLACEHOLDER: "Search for users",
    GROUPS_PLACEHOLDER: "Search for groups",
    ADD_USER_TEXT: "Add new user",
    ADD_GROUP_TEXT: "Add new group",
    REMOVE_TEXT: "Remove",
    ASSIGN_USERS_ONLY_DESCRIPTION: "Select any user who is registered with the Access Console.",
    ASSIGN_GROUP_ONLY_DESCRIPTION: "Select any group available on the Access Console.",

    CREATE_TEMPLATE: "Create template",
    UPDATE_TEMPLATE: "Update template",
    SESSION_TEMPLATE_REQUIRED: "Session template required.",
    USER_OR_GROUP_REQUIRED: "User or group required",

    CREATE_TEMPLATE_URL: "/admin/sessionTemplates/createTemplate",
    EDIT_TEMPLATE_URL: templateId => `/admin/sessionTemplates/${templateId}/editTemplate/`,
    ASSIGN_USERS_URL: templateId => `/admin/sessionTemplates/${templateId}/assignUsersAndGroups/`,

    CONSOLE_PNG: "/console-session.png",
    VIRTUAL_PNG: "/virtual-session.png",
    ADD_USERS: "Add users",
    ADD_GROUPS: "Add groups",

}
