// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

export const SESSION_TEMPLATES_TABLE_CONSTANTS = {
    LOADING_TEXT: "Loading session templates",
    EMPTY_TEXT: "No available session templates.",
    CONTACT_TEXT: "Contact your system administrator.",
    SESSION_TEMPLATES: "Session templates",
    HEADER_DESCRIPTION: "All of your available session templates are listed here.",
    CREATE_TEMPLATE_TEXT: "Create template",
    VIEW_USER_DETAILS_BUTTON: "View details",

    ID: "Id",
    NAME_ID: "Name",
    DESCRIPTION_ID: "Description",
    OS_FAMILY_ID: "OsFamily",
    OS_VERSIONS_ID: "OsVersions",
    INSTANCE_TYPES_ID: "InstanceTypes",
    INSTANCE_IDS_ID: "InstanceIds",
    INSTANCE_REGIONS_ID: "InstanceRegions",
    HOST_NUM_OF_CPUS_ID: "HostNumberOfCpus",
    HOST_MEMORY_ID: "HostMemoryTotalBytes",
    CREATED_BY_ID: "CreatedBy",
    CREATION_TIME_ID: "CreationTime",
    LAST_MODIFIED_BY_ID: "LastModifiedBy",
    LAST_MODIFIED_TIME_ID: "LastModifiedTime",
    USER_PUBLISHED_TO_ID: "UsersPublishedTo",
    GROUPS_PUBLISHED_TO_ID: "GroupsPublishedTo",
    TYPE_ID: "Type",
    DCV_GL_ENABLED_ID: "DcvGlEnabled",
    MAX_CONCURRENT_CLIENTS_ID: "MaxConcurrentClients",
    INIT_FILE_ID: "InitFile",
    AUTORUN_FILE_ID: "AutorunFile",
    AUTORUN_FILE_ARGUMENTS_ID: "AutorunFileArguments",
    PERMISSIONS_FILE_ID: "PermissionsFile",
    REQUIREMENTS_ID: "Requirements",
    ENQUEUE_REQUEST_ID: "EnqueueRequest",
    DISABLE_RETRY_ON_FAILURE_ID: "DisableRetryOnFailure",
    STORAGE_ROOT_ID: "StorageRoot",

    NAME_HEADER: "Name",
    DESCRIPTION_HEADER: "Description",
    OS_FAMILY_HEADER: "Operating system",
    OS_VERSIONS_HEADER: "OS versions",
    INSTANCE_TYPES_HEADER: "Instance types",
    INSTANCE_IDS_HEADER: "Instance IDs",
    INSTANCE_REGIONS_HEADER: "Instance regions",
    HOST_NUM_OF_CPUS_HEADER: "Host vCPUs",
    HOST_MEMORY_HEADER: "Host Memory",
    CREATED_BY_HEADER: "Created by",
    CREATION_TIME_HEADER: "Creation time",
    LAST_MODIFIED_BY_HEADER: "Last modified by",
    LAST_MODIFIED_TIME_HEADER: "Last modified time",
    USER_PUBLISHED_TO_HEADER: "Users",
    GROUPS_PUBLISHED_TO_HEADER: "Groups",
    TYPE_HEADER: "Session type",
    DCV_GL_ENABLED_HEADER: "OpenGL",
    MAX_CONCURRENT_CLIENTS_HEADER: "Max concurrent clients",
    INIT_FILE_HEADER: "Init file",
    AUTORUN_FILE_HEADER: "Autorun file",
    AUTORUN_FILE_ARGUMENTS_HEADER: "Autorun file arguments",
    PERMISSIONS_FILE_HEADER: "Permissions file",
    REQUIREMENTS_HEADER: "Requirements",
    ENQUEUE_REQUEST_HEADER: "Enqueue request",
    DISABLE_RETRY_ON_FAILURE_HEADER: "Disable retry on failure",
    STORAGE_ROOT_HEADER: "Storage root",

    UNKNOWN: "UNKNOWN"
}
