export const USER_GROUP_SESSION_TEMPLATE_DETAILS_CONSTANTS = {
    SESSION_TEMPLATES_HEADER: "Session templates",
    EMPTY_TEXT: "No session templates available",

    SESSION_TEMPLATE_NAME_ID: "name",
    SESSION_TEMPLATE_NAME_HEADER: "Name",

    SESSION_TEMPLATE_DESCRIPTION_ID: "description",
    SESSION_TEMPLATE_DESCRIPTION_HEADER: "Description",

    SESSION_TEMPLATE_OPERATING_SYSTEM_ID: "operatingSystem",
    SESSION_TEMPLATE_OPERATING_SYSTEM_HEADER: "Operating system",

    SESSION_TEMPLATE_INSTANCE_TYPES_ID: "instanceTypes",
    SESSION_TEMPLATE_INSTANCE_TYPES_HEADER: "Instance types",

    SESSION_TEMPLATE_SESSION_TYPES_ID: "sessionType",
    SESSION_TEMPLATE_SESSION_TYPES_HEADER: "Session type",

    SESSION_TEMPLATE_OS_ID: "os",
    SESSION_TEMPLATE_OS_HEADER: "OS",

    LOADING_TEXT: "Loading session templates",

    REMOVE_SESSION_TEMPLATE_BUTTON: "Remove",
    ADD_SESSION_TEMPLATE_BUTTON: "Add template",
}