name: Trigger Integration Tests workflow

on:
  push:
    branches:
      - main
      
permissions:
  id-token: write
  contents: read

jobs:
  trigger:
    runs-on: ubuntu-latest
    
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ROLE_ARN}}
          aws-region: ${{secrets.REGION}}

      - uses: aws-actions/aws-codepipeline-trigger@v1
        with:
          pipeline-name: ${{secrets.CODEPIPELINE}}
