name: Trigger Integration Tests workflow

on:
  push:
    branches:
      - main
      
permissions:
  id-token: write
  contents: read

jobs:
  trigger:
    runs-on: ubuntu-latest
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ROLE_ARN}}
          aws-region: ${{secrets.REGION}}
          
      - name: Trigger CodePipeline
        run: aws codepipeline start-pipeline-execution --name ${{secrets.CODEPIPELINE}}
